//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PaginaWebCatalogosEntities : DbContext
    {
        public PaginaWebCatalogosEntities()
            : base("name=PaginaWebCatalogosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<paObtenerTipoProductosActivos_Result> paObtenerTipoProductosActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTipoProductosActivos_Result>("paObtenerTipoProductosActivos");
        }
    
        public virtual ObjectResult<paObtenerMenuPublicoActivo_Result> paObtenerMenuPublicoActivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerMenuPublicoActivo_Result>("paObtenerMenuPublicoActivo");
        }
    
        public virtual ObjectResult<paObtenerImagenesXTipoSubtipo_Result> paObtenerImagenesXTipoSubtipo(Nullable<int> idTipoProducto, Nullable<int> idSubTipo)
        {
            var idTipoProductoParameter = idTipoProducto.HasValue ?
                new ObjectParameter("IdTipoProducto", idTipoProducto) :
                new ObjectParameter("IdTipoProducto", typeof(int));
    
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerImagenesXTipoSubtipo_Result>("paObtenerImagenesXTipoSubtipo", idTipoProductoParameter, idSubTipoParameter);
        }
    
        public virtual int paInsertarUsuario(string identificacion, string nombre, string primerApellido, string segundoApellido, string correoElectronico, Nullable<int> telefono, string direccion, Nullable<bool> genero, string usuarioCreacion, ObjectParameter respuesta, ObjectParameter idUsuario)
        {
            var identificacionParameter = identificacion != null ?
                new ObjectParameter("Identificacion", identificacion) :
                new ObjectParameter("Identificacion", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var generoParameter = genero.HasValue ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(bool));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarUsuario", identificacionParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, correoElectronicoParameter, telefonoParameter, direccionParameter, generoParameter, usuarioCreacionParameter, respuesta, idUsuario);
        }
    
        public virtual int paInsertarLogin(Nullable<int> idUsuario, string usuario, string contrasena, ObjectParameter respuesta)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarLogin", idUsuarioParameter, usuarioParameter, contrasenaParameter, respuesta);
        }
    
        public virtual int paValidarLogueo(string usuario, string contrasena, ObjectParameter correcto)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paValidarLogueo", usuarioParameter, contrasenaParameter, correcto);
        }
    
        public virtual ObjectResult<paObtenerInfoUsuario_Result> paObtenerInfoUsuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerInfoUsuario_Result>("paObtenerInfoUsuario", usuarioParameter);
        }
    
        public virtual int paInsertarProductoCarrito(Nullable<int> idProducto, Nullable<int> idUsuario, ObjectParameter respuesta)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarProductoCarrito", idProductoParameter, idUsuarioParameter, respuesta);
        }
    
        public virtual int paEliminarProductoCarro(Nullable<int> idProducto, Nullable<int> idUsuario)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarProductoCarro", idProductoParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<paObtenerMenuXUsuario_Result> paObtenerMenuXUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerMenuXUsuario_Result>("paObtenerMenuXUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<paObtenerIconos_Result> paObtenerIconos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerIconos_Result>("paObtenerIconos");
        }
    
        public virtual ObjectResult<paObtenerIconosRedes_Result> paObtenerIconosRedes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerIconosRedes_Result>("paObtenerIconosRedes");
        }
    
        public virtual int paInsertarRedSocial(string nombre, string descripcion, string url, string icono, string usuarioCreacion, string color, ObjectParameter respuesta)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var iconoParameter = icono != null ?
                new ObjectParameter("Icono", icono) :
                new ObjectParameter("Icono", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarRedSocial", nombreParameter, descripcionParameter, urlParameter, iconoParameter, usuarioCreacionParameter, colorParameter, respuesta);
        }
    
        public virtual ObjectResult<paObtenerRedesSociales_Result> paObtenerRedesSociales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerRedesSociales_Result>("paObtenerRedesSociales");
        }
    
        public virtual int paInsertarTipoProducto(string codigo, string nombre, string descripcion, string usuarioCreacion, ObjectParameter respuesta)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarTipoProducto", codigoParameter, nombreParameter, descripcionParameter, usuarioCreacionParameter, respuesta);
        }
    
        public virtual ObjectResult<paObtenerTipoProductoActivo_Result> paObtenerTipoProductoActivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTipoProductoActivo_Result>("paObtenerTipoProductoActivo");
        }
    
        public virtual int paInsertarRelacionTipoSubTipo(Nullable<int> idTipo, Nullable<int> idSubTipo)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarRelacionTipoSubTipo", idTipoParameter, idSubTipoParameter);
        }
    
        public virtual int paInsertarSubTipoProducto(string codigo, string nombre, string descripcion, string usuarioCreacion, ObjectParameter respuesta, ObjectParameter idSubTipo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarSubTipoProducto", codigoParameter, nombreParameter, descripcionParameter, usuarioCreacionParameter, respuesta, idSubTipo);
        }
    
        public virtual int paInsertarMenuPublico(Nullable<int> idTipo, Nullable<int> idSubTipo)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarMenuPublico", idTipoParameter, idSubTipoParameter);
        }
    
        public virtual ObjectResult<paObtenerSubTipoProdActivo_Result> paObtenerSubTipoProdActivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerSubTipoProdActivo_Result>("paObtenerSubTipoProdActivo");
        }
    
        public virtual int paInsertarImagen(string nombre, string raiz, string url, string usuarioCreacion, ObjectParameter idImagen)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var raizParameter = raiz != null ?
                new ObjectParameter("Raiz", raiz) :
                new ObjectParameter("Raiz", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarImagen", nombreParameter, raizParameter, urlParameter, usuarioCreacionParameter, idImagen);
        }
    
        public virtual int paInsertarRelacionImagenProducto(Nullable<int> idProducto, Nullable<int> idImagen, Nullable<int> idUsuario, ObjectParameter idRelacion)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarRelacionImagenProducto", idProductoParameter, idImagenParameter, idUsuarioParameter, idRelacion);
        }
    
        public virtual int paActualizarRedSocial(Nullable<int> idRedSocial, string nombre, string descripcion, string url, string icono, string color, string usuarioUltimaModificacion)
        {
            var idRedSocialParameter = idRedSocial.HasValue ?
                new ObjectParameter("IdRedSocial", idRedSocial) :
                new ObjectParameter("IdRedSocial", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var iconoParameter = icono != null ?
                new ObjectParameter("Icono", icono) :
                new ObjectParameter("Icono", typeof(string));
    
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            var usuarioUltimaModificacionParameter = usuarioUltimaModificacion != null ?
                new ObjectParameter("UsuarioUltimaModificacion", usuarioUltimaModificacion) :
                new ObjectParameter("UsuarioUltimaModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paActualizarRedSocial", idRedSocialParameter, nombreParameter, descripcionParameter, urlParameter, iconoParameter, colorParameter, usuarioUltimaModificacionParameter);
        }
    
        public virtual ObjectResult<paObtenerRedSocial_Result> paObtenerRedSocial(Nullable<int> idRedSocial)
        {
            var idRedSocialParameter = idRedSocial.HasValue ?
                new ObjectParameter("IdRedSocial", idRedSocial) :
                new ObjectParameter("IdRedSocial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerRedSocial_Result>("paObtenerRedSocial", idRedSocialParameter);
        }
    
        public virtual ObjectResult<paObtenerTodasRedesSociales_Result> paObtenerTodasRedesSociales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTodasRedesSociales_Result>("paObtenerTodasRedesSociales");
        }
    
        public virtual ObjectResult<paObtenerTodosTipos_Result> paObtenerTodosTipos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTodosTipos_Result>("paObtenerTodosTipos");
        }
    
        public virtual ObjectResult<paObtenerTodosProductos_Result> paObtenerTodosProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTodosProductos_Result>("paObtenerTodosProductos");
        }
    
        public virtual int paDesactivarActivarRedSocial(Nullable<int> idRedSocial, Nullable<bool> idEstado)
        {
            var idRedSocialParameter = idRedSocial.HasValue ?
                new ObjectParameter("IdRedSocial", idRedSocial) :
                new ObjectParameter("IdRedSocial", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDesactivarActivarRedSocial", idRedSocialParameter, idEstadoParameter);
        }
    
        public virtual int paEliminarRedSocial(Nullable<int> idRedSocial)
        {
            var idRedSocialParameter = idRedSocial.HasValue ?
                new ObjectParameter("IdRedSocial", idRedSocial) :
                new ObjectParameter("IdRedSocial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarRedSocial", idRedSocialParameter);
        }
    
        public virtual int paDesactivarActivarProducto(Nullable<int> idProducto, Nullable<bool> estado)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDesactivarActivarProducto", idProductoParameter, estadoParameter);
        }
    
        public virtual int paDesactivarActivarSubTipo(Nullable<int> idSubTipo, Nullable<bool> estado)
        {
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDesactivarActivarSubTipo", idSubTipoParameter, estadoParameter);
        }
    
        public virtual int paDesactivarActivarTipo(Nullable<int> idTipo, Nullable<bool> estado)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDesactivarActivarTipo", idTipoParameter, estadoParameter);
        }
    
        public virtual ObjectResult<paObtenerTipoXId_Result> paObtenerTipoXId(Nullable<int> idTipo)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTipoXId_Result>("paObtenerTipoXId", idTipoParameter);
        }
    
        public virtual int paActualizarDatosTipo(Nullable<int> idTipo, string codigo, string nombre, string descripcion)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paActualizarDatosTipo", idTipoParameter, codigoParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int paActualizarSubTipo(Nullable<int> idSubTipo, string codigo, string nombre, string descripcion, string usuarioUltimaModificacion)
        {
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioUltimaModificacionParameter = usuarioUltimaModificacion != null ?
                new ObjectParameter("UsuarioUltimaModificacion", usuarioUltimaModificacion) :
                new ObjectParameter("UsuarioUltimaModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paActualizarSubTipo", idSubTipoParameter, codigoParameter, nombreParameter, descripcionParameter, usuarioUltimaModificacionParameter);
        }
    
        public virtual ObjectResult<paObtenerSubTipoXId_Result> paObtenerSubTipoXId(Nullable<int> idSubTipo)
        {
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerSubTipoXId_Result>("paObtenerSubTipoXId", idSubTipoParameter);
        }
    
        public virtual int paEliminarProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarProducto", idProductoParameter);
        }
    
        public virtual int paActualizarTipo(Nullable<int> idTipo, string codigo, string nombre, string descripcion, string usuarioUltimaModificacion)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var usuarioUltimaModificacionParameter = usuarioUltimaModificacion != null ?
                new ObjectParameter("UsuarioUltimaModificacion", usuarioUltimaModificacion) :
                new ObjectParameter("UsuarioUltimaModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paActualizarTipo", idTipoParameter, codigoParameter, nombreParameter, descripcionParameter, usuarioUltimaModificacionParameter);
        }
    
        public virtual int paEliminarSubTipo(Nullable<int> idSubTipo)
        {
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarSubTipo", idSubTipoParameter);
        }
    
        public virtual ObjectResult<paObtenerSubTiposXIdTipo_Result> paObtenerSubTiposXIdTipo(Nullable<int> idTipo)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerSubTiposXIdTipo_Result>("paObtenerSubTiposXIdTipo", idTipoParameter);
        }
    
        public virtual ObjectResult<paObtenerImagenesXIdProducto_Result> paObtenerImagenesXIdProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerImagenesXIdProducto_Result>("paObtenerImagenesXIdProducto", idProductoParameter);
        }
    
        public virtual int paEliminarImagenXId(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarImagenXId", idImagenParameter);
        }
    
        public virtual ObjectResult<paObtenerImagenXId_Result> paObtenerImagenXId(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerImagenXId_Result>("paObtenerImagenXId", idImagenParameter);
        }
    
        public virtual ObjectResult<paObtenerRutaImagen_Result> paObtenerRutaImagen(Nullable<int> idImagen)
        {
            var idImagenParameter = idImagen.HasValue ?
                new ObjectParameter("IdImagen", idImagen) :
                new ObjectParameter("IdImagen", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerRutaImagen_Result>("paObtenerRutaImagen", idImagenParameter);
        }
    
        public virtual ObjectResult<paObtenerTodosSubTipos_Result> paObtenerTodosSubTipos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTodosSubTipos_Result>("paObtenerTodosSubTipos");
        }
    
        public virtual int paDesactivarActivarBanner(Nullable<int> idBanner, Nullable<int> tipo)
        {
            var idBannerParameter = idBanner.HasValue ?
                new ObjectParameter("IdBanner", idBanner) :
                new ObjectParameter("IdBanner", typeof(int));
    
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("Tipo", tipo) :
                new ObjectParameter("Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDesactivarActivarBanner", idBannerParameter, tipoParameter);
        }
    
        public virtual int paEliminarbanner(Nullable<int> idBanner)
        {
            var idBannerParameter = idBanner.HasValue ?
                new ObjectParameter("IdBanner", idBanner) :
                new ObjectParameter("IdBanner", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarbanner", idBannerParameter);
        }
    
        public virtual int paInsertarBannerPrincipal(string nombre, string raiz, string url, string titulo, string detalle, string usuarioCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var raizParameter = raiz != null ?
                new ObjectParameter("Raiz", raiz) :
                new ObjectParameter("Raiz", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarBannerPrincipal", nombreParameter, raizParameter, urlParameter, tituloParameter, detalleParameter, usuarioCreacionParameter);
        }
    
        public virtual ObjectResult<paObtenerBanners_Result> paObtenerBanners()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerBanners_Result>("paObtenerBanners");
        }
    
        public virtual ObjectResult<paObtenerBannersActivos_Result> paObtenerBannersActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerBannersActivos_Result>("paObtenerBannersActivos");
        }
    
        public virtual ObjectResult<paObtenerDetalleProducto_Result> paObtenerDetalleProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerDetalleProducto_Result>("paObtenerDetalleProducto", idProductoParameter);
        }
    
        public virtual int paEliminarTipo(Nullable<int> idTipo, ObjectParameter correcto, ObjectParameter descripcionTipo)
        {
            var idTipoParameter = idTipo.HasValue ?
                new ObjectParameter("IdTipo", idTipo) :
                new ObjectParameter("IdTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarTipo", idTipoParameter, correcto, descripcionTipo);
        }
    
        public virtual int paDesactivarActivarBeneficio(Nullable<int> idBeneficio, Nullable<bool> estado)
        {
            var idBeneficioParameter = idBeneficio.HasValue ?
                new ObjectParameter("IdBeneficio", idBeneficio) :
                new ObjectParameter("IdBeneficio", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paDesactivarActivarBeneficio", idBeneficioParameter, estadoParameter);
        }
    
        public virtual int paEliminarBeneficio(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paEliminarBeneficio", idParameter);
        }
    
        public virtual ObjectResult<paObtenerBeneficiosActivos_Result> paObtenerBeneficiosActivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerBeneficiosActivos_Result>("paObtenerBeneficiosActivos");
        }
    
        public virtual ObjectResult<paObtenerTodosLosBeneficios_Result> paObtenerTodosLosBeneficios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerTodosLosBeneficios_Result>("paObtenerTodosLosBeneficios");
        }
    
        public virtual int paInsertarProducto(string codigo, string nombre, string descripcion, string moneda, Nullable<decimal> precioProducto, Nullable<int> condicion, Nullable<int> tipoProducto, Nullable<int> subTipo, Nullable<bool> descuento, Nullable<int> tipoDescuento, Nullable<decimal> cantidadDescuento, string usuarioCreacion, ObjectParameter idProducto)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var monedaParameter = moneda != null ?
                new ObjectParameter("Moneda", moneda) :
                new ObjectParameter("Moneda", typeof(string));
    
            var precioProductoParameter = precioProducto.HasValue ?
                new ObjectParameter("PrecioProducto", precioProducto) :
                new ObjectParameter("PrecioProducto", typeof(decimal));
    
            var condicionParameter = condicion.HasValue ?
                new ObjectParameter("Condicion", condicion) :
                new ObjectParameter("Condicion", typeof(int));
    
            var tipoProductoParameter = tipoProducto.HasValue ?
                new ObjectParameter("TipoProducto", tipoProducto) :
                new ObjectParameter("TipoProducto", typeof(int));
    
            var subTipoParameter = subTipo.HasValue ?
                new ObjectParameter("SubTipo", subTipo) :
                new ObjectParameter("SubTipo", typeof(int));
    
            var descuentoParameter = descuento.HasValue ?
                new ObjectParameter("Descuento", descuento) :
                new ObjectParameter("Descuento", typeof(bool));
    
            var tipoDescuentoParameter = tipoDescuento.HasValue ?
                new ObjectParameter("TipoDescuento", tipoDescuento) :
                new ObjectParameter("TipoDescuento", typeof(int));
    
            var cantidadDescuentoParameter = cantidadDescuento.HasValue ?
                new ObjectParameter("CantidadDescuento", cantidadDescuento) :
                new ObjectParameter("CantidadDescuento", typeof(decimal));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarProducto", codigoParameter, nombreParameter, descripcionParameter, monedaParameter, precioProductoParameter, condicionParameter, tipoProductoParameter, subTipoParameter, descuentoParameter, tipoDescuentoParameter, cantidadDescuentoParameter, usuarioCreacionParameter, idProducto);
        }
    
        public virtual ObjectResult<paObtenerInfoProductoXId_Result> paObtenerInfoProductoXId(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerInfoProductoXId_Result>("paObtenerInfoProductoXId", idProductoParameter);
        }
    
        public virtual int paActualizarProducto(Nullable<int> idProducto, string codigo, string nombre, string descripcion, string moneda, Nullable<decimal> precioUnitario, Nullable<int> condicion, Nullable<int> tipoProducto, Nullable<int> subTipo, Nullable<bool> descuento, Nullable<int> tipoDescuiento, Nullable<decimal> cantidadDescuento, string usuarioUltimaModificacion)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var monedaParameter = moneda != null ?
                new ObjectParameter("Moneda", moneda) :
                new ObjectParameter("Moneda", typeof(string));
    
            var precioUnitarioParameter = precioUnitario.HasValue ?
                new ObjectParameter("PrecioUnitario", precioUnitario) :
                new ObjectParameter("PrecioUnitario", typeof(decimal));
    
            var condicionParameter = condicion.HasValue ?
                new ObjectParameter("Condicion", condicion) :
                new ObjectParameter("Condicion", typeof(int));
    
            var tipoProductoParameter = tipoProducto.HasValue ?
                new ObjectParameter("TipoProducto", tipoProducto) :
                new ObjectParameter("TipoProducto", typeof(int));
    
            var subTipoParameter = subTipo.HasValue ?
                new ObjectParameter("SubTipo", subTipo) :
                new ObjectParameter("SubTipo", typeof(int));
    
            var descuentoParameter = descuento.HasValue ?
                new ObjectParameter("Descuento", descuento) :
                new ObjectParameter("Descuento", typeof(bool));
    
            var tipoDescuientoParameter = tipoDescuiento.HasValue ?
                new ObjectParameter("TipoDescuiento", tipoDescuiento) :
                new ObjectParameter("TipoDescuiento", typeof(int));
    
            var cantidadDescuentoParameter = cantidadDescuento.HasValue ?
                new ObjectParameter("CantidadDescuento", cantidadDescuento) :
                new ObjectParameter("CantidadDescuento", typeof(decimal));
    
            var usuarioUltimaModificacionParameter = usuarioUltimaModificacion != null ?
                new ObjectParameter("UsuarioUltimaModificacion", usuarioUltimaModificacion) :
                new ObjectParameter("UsuarioUltimaModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paActualizarProducto", idProductoParameter, codigoParameter, nombreParameter, descripcionParameter, monedaParameter, precioUnitarioParameter, condicionParameter, tipoProductoParameter, subTipoParameter, descuentoParameter, tipoDescuientoParameter, cantidadDescuentoParameter, usuarioUltimaModificacionParameter);
        }
    
        public virtual ObjectResult<paObtenerProductosDescuentoRandom_Result> paObtenerProductosDescuentoRandom()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerProductosDescuentoRandom_Result>("paObtenerProductosDescuentoRandom");
        }
    
        public virtual ObjectResult<paObtenerProductosRandom_Result> paObtenerProductosRandom()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerProductosRandom_Result>("paObtenerProductosRandom");
        }
    
        public virtual ObjectResult<paObtenerProductoPorTipo_Result> paObtenerProductoPorTipo(Nullable<int> idTipoProducto, Nullable<int> idSubTipo)
        {
            var idTipoProductoParameter = idTipoProducto.HasValue ?
                new ObjectParameter("IdTipoProducto", idTipoProducto) :
                new ObjectParameter("IdTipoProducto", typeof(int));
    
            var idSubTipoParameter = idSubTipo.HasValue ?
                new ObjectParameter("IdSubTipo", idSubTipo) :
                new ObjectParameter("IdSubTipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerProductoPorTipo_Result>("paObtenerProductoPorTipo", idTipoProductoParameter, idSubTipoParameter);
        }
    
        public virtual int paInsertarBeneficios(string nombre, string descripcion, string icono, string usuarioCreacion, ObjectParameter idBeneficio)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iconoParameter = icono != null ?
                new ObjectParameter("Icono", icono) :
                new ObjectParameter("Icono", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion != null ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarBeneficios", nombreParameter, descripcionParameter, iconoParameter, usuarioCreacionParameter, idBeneficio);
        }
    
        public virtual int paActualizarBeneficio(Nullable<int> id, string nombre, string descripcion, string icono, string usuarioUltimaModificacion)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var iconoParameter = icono != null ?
                new ObjectParameter("Icono", icono) :
                new ObjectParameter("Icono", typeof(string));
    
            var usuarioUltimaModificacionParameter = usuarioUltimaModificacion != null ?
                new ObjectParameter("UsuarioUltimaModificacion", usuarioUltimaModificacion) :
                new ObjectParameter("UsuarioUltimaModificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paActualizarBeneficio", idParameter, nombreParameter, descripcionParameter, iconoParameter, usuarioUltimaModificacionParameter);
        }
    
        public virtual ObjectResult<paObtenerBeneficioXId_Result> paObtenerBeneficioXId(Nullable<int> idBeneficio)
        {
            var idBeneficioParameter = idBeneficio.HasValue ?
                new ObjectParameter("IdBeneficio", idBeneficio) :
                new ObjectParameter("IdBeneficio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerBeneficioXId_Result>("paObtenerBeneficioXId", idBeneficioParameter);
        }
    
        public virtual int paInsertarInformacionEmpresa(string nombre, string descripcion, string correoElectronico, Nullable<int> telefono, string direccion, string raiz, string mapa, ObjectParameter resultado)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var raizParameter = raiz != null ?
                new ObjectParameter("Raiz", raiz) :
                new ObjectParameter("Raiz", typeof(string));
    
            var mapaParameter = mapa != null ?
                new ObjectParameter("Mapa", mapa) :
                new ObjectParameter("Mapa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paInsertarInformacionEmpresa", nombreParameter, descripcionParameter, correoElectronicoParameter, telefonoParameter, direccionParameter, raizParameter, mapaParameter, resultado);
        }
    
        public virtual ObjectResult<paObtenerInformacionEmpresa_Result> paObtenerInformacionEmpresa()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerInformacionEmpresa_Result>("paObtenerInformacionEmpresa");
        }
    
        public virtual int paActualizarInformacionEmpresa(Nullable<int> idEmpresa, string nombreEmpresa, string descripcion, string correo, Nullable<int> telefono, string direccion, string nombreImagen, string mapa, string raiz)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var nombreEmpresaParameter = nombreEmpresa != null ?
                new ObjectParameter("NombreEmpresa", nombreEmpresa) :
                new ObjectParameter("NombreEmpresa", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var telefonoParameter = telefono.HasValue ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(int));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var nombreImagenParameter = nombreImagen != null ?
                new ObjectParameter("NombreImagen", nombreImagen) :
                new ObjectParameter("NombreImagen", typeof(string));
    
            var mapaParameter = mapa != null ?
                new ObjectParameter("Mapa", mapa) :
                new ObjectParameter("Mapa", typeof(string));
    
            var raizParameter = raiz != null ?
                new ObjectParameter("Raiz", raiz) :
                new ObjectParameter("Raiz", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("paActualizarInformacionEmpresa", idEmpresaParameter, nombreEmpresaParameter, descripcionParameter, correoParameter, telefonoParameter, direccionParameter, nombreImagenParameter, mapaParameter, raizParameter);
        }
    
        public virtual ObjectResult<paObtenerCarrito_Result> paObtenerCarrito(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paObtenerCarrito_Result>("paObtenerCarrito", idUsuarioParameter);
        }
    }
}
